#!/bin/sh
# Run the pipeui CLI robustly from this checkout.
#
# Why this exists: the repo lives under an iCloud path containing a space
# ("Mobile Documents"), which breaks site.py's processing of editable-install
# .pth files in this venv — so `import pipeui` fails for the generated
# `pipeui` console script (`pipeui start`, `uv run pipeui start`).
# Setting PYTHONPATH=src puts the package on sys.path directly (interpreter
# level), bypassing the broken .pth. Unlike the venv launcher, this file is
# NOT regenerated by `uv sync` / `uv run`, so it stays fixed.
#
# Usage:
#   ./start.sh           # -> pipeui start  (runs the app; Ctrl-C to stop)
#   ./start.sh init      # -> pipeui init
#   ./start.sh --help    # -> pipeui --help
cd "$(dirname "$0")" || exit 1
exec env PYTHONPATH=src .venv/bin/pipeui "${@:-start}"
