#!/bin/sh
# Run the pipeui CLI robustly from this checkout.
#
# Why this exists: the repo lives under an iCloud path containing a space
# ("Mobile Documents"), which breaks site.py's processing of editable-install
# .pth files in this venv — so `import pipeui` fails for the generated
# `pipeui` console script (`pipeui start`, `uv run pipeui start`).
# Setting PYTHONPATH=src puts the package on sys.path directly (interpreter
# level), bypassing the broken .pth. Unlike the venv launcher, this file is
# NOT regenerated by `uv sync` / `uv run`, so it stays fixed.
#
# We invoke the package with `python -m pipeui.app.cli` rather than the generated
# `pipeui` console script: that script hard-codes the entry-point import path and
# drifts stale when the package is reorganized (it pointed at the moved
# `pipeui.cli` and raised ModuleNotFoundError). `-m` resolves the module live, so
# it stays correct across refactors.
#
# Usage:
#   ./start.sh           # -> pipeui start  (runs the app; Ctrl-C to stop)
#   ./start.sh init      # -> pipeui init
cd "$(dirname "$0")" || exit 1
exec env PYTHONPATH=src .venv/bin/python -m pipeui.app.cli "${@:-start}"
